import { assertNever, type Refinement, type TypeExpr } from "../ast.ts";
import { refinementBodyJs, refinementToJs } from "../refinements.ts";
import type { PrimName } from "../stdlib-types.ts";
import type { GenCtx } from "./context.ts";

export type GenDescData = { t: string; [k: string]: unknown };

/**
 * The generation descriptor of a `for-all` type (testing.md §8.3.2), or why it
 * has none. Both readers take this one answer: the checker reports a refusal
 * as E0715 at the `for-all` field, and codegen emits the descriptor. A type
 * the checker accepts is therefore one the runtime's generator builds in full;
 * none of it is left for the runtime to stand in for with a placeholder.
 */
export function forAllGenerator(
  t: TypeExpr,
  gen: Pick<GenCtx, "types">,
): { desc: GenDescData } | { refused: string } {
  try {
    return { desc: boundRecursion(describe(t, gen, TOP_LEVEL), new Map()) };
  } catch (e) {
    if (e instanceof NoGenerator) return { refused: e.message };
    throw e;
  }
}

/** E0715's message, shared by the checker and codegen's last-line throw. */
export function noGeneratorMessage(variable: string, reason: string): string {
  return `No generator for \`for-all\` "${variable}": ${reason}`;
}

/** A part of a `for-all` type the generator cannot build; the message says which. */
class NoGenerator extends Error {}

/**
 * Where a type expression is read: the named types being expanded on the way
 * to it, each with the key of the arguments it was applied to, and — inside a
 * generic's body — the descriptor each parameter was applied to. A name met
 * again while it is being expanded is a recursive step (`Rec`), which is only
 * a step back into the same type when it is applied to the same arguments.
 */
type Expansion = {
  open: ReadonlyMap<string, string>;
  params: ReadonlyMap<string, GenDescData | undefined>;
};

const TOP_LEVEL: Expansion = { open: new Map(), params: new Map() };

function describe(t: TypeExpr, gen: Pick<GenCtx, "types">, at: Expansion): GenDescData {
  switch (t.kind) {
    case "TypePrim":
      return primDesc(t.name);
    case "TypeRef": {
      if (!at.params.has(t.name)) return named(t.name, [], gen, at);
      const arg = at.params.get(t.name);
      if (!arg) throw new NoGenerator(`type parameter "${t.name}" has no argument`);
      return arg;
    }
    case "TypeApp": {
      const args = t.args.map((a) => describe(a, gen, at));
      const arg = (i: number): GenDescData => {
        const a = args[i];
        if (!a) throw new NoGenerator(`"${t.name}" is missing an argument`);
        return a;
      };
      switch (t.name) {
        case "List":
        case "Set":
          return { t: t.name, elem: arg(0) };
        case "Map":
          return { t: "Map", key: arg(0), val: arg(1) };
        case "Option":
          return { t: "Option", inner: arg(0) };
        case "Result":
          return { t: "Result", ok: arg(0), err: arg(1) };
        // The same array a tuple literal lowers to, each element generated by
        // its own descriptor — refinements included.
        case "Tuple":
          return { t: "Tuple", items: args };
        default:
          return named(t.name, args, gen, at);
      }
    }
    case "TypeNominal":
    case "TypeRefinement":
      return applyRefine(describe(t.inner, gen, at), t.refinement);
    case "TypeRecord":
      return {
        t: "Record",
        fields: t.fields.map((f) => ({ name: f.name, desc: describe(f.type, gen, at) })),
      };
    case "TypeUnion":
      return {
        t: "Union",
        variants: t.variants.map((v) => ({
          name: v.name,
          payloads: v.payloads.map((p) => describe(p, gen, at)),
        })),
      };
    default:
      assertNever(t);
      throw new NoGenerator("the type is not one the generator knows");
  }
}

function primDesc(name: PrimName): GenDescData {
  switch (name) {
    case "Int":
    case "Time":
      return { t: "Int" };
    case "Float":
      return { t: "Float" };
    case "Text":
    case "Bytes":
      return { t: "Text" };
    case "Bool":
      return { t: "Bool" };
    // `()`, the one value, which lowers to `null`.
    case "Unit":
      return { t: "Unit" };
    // A `File` comes from the platform and an `EffectId` from `emit`; neither
    // has a value the generator could make up.
    case "File":
    case "EffectId":
      throw new NoGenerator(`"${name}" has none`);
    default:
      assertNever(name);
      throw new NoGenerator(`"${String(name)}" has none`);
  }
}

/**
 * A named type applied to `args`: its body, read with its parameters bound to
 * them. Inside its own expansion the name is a step back into it (`Rec`), and
 * a body that takes one is wrapped as the recursive type it is (`Fix`).
 */
function named(
  name: string,
  args: GenDescData[],
  gen: Pick<GenCtx, "types">,
  at: Expansion,
): GenDescData {
  const key = JSON.stringify(args);
  const open = at.open.get(name);
  if (open !== undefined) {
    if (open === key) return { t: "Rec", name };
    // `type Grow(T) = Stop | Deeper(Grow(List(T)))`: each step is a different
    // type, so there is no one body to step back into.
    throw new NoGenerator(`"${name}" applies itself to a different argument`);
  }
  const def = gen.types.get(name);
  if (!def) throw new NoGenerator(`"${name}" names no type`);
  const params = new Map(def.params.map((p, i) => [p, args[i]]));
  const body = describe(def.body, gen, { open: new Map([...at.open, [name, key]]), params });
  return stepsInto(body, name) ? { t: "Fix", name, body } : body;
}

/** The descriptor kinds that hold other descriptors, as the recursion bound reads them. */
type Structured =
  | { t: "List" | "Set"; elem: GenDescData }
  | { t: "Map"; key: GenDescData; val: GenDescData }
  | { t: "Option"; inner: GenDescData }
  | { t: "Result"; ok: GenDescData; err: GenDescData }
  | { t: "Record"; fields: { name: string; desc: GenDescData }[] }
  | { t: "Tuple"; items: GenDescData[] }
  | { t: "Union"; variants: { name: string; payloads: GenDescData[] }[] }
  | { t: "Fix"; name: string; body: GenDescData }
  | { t: "Rec"; name: string }
  | { t: "Int" | "Float" | "Text" | "Bool" | "Unit" };

/** The descriptors directly inside `d`. */
function partsOf(d: GenDescData): GenDescData[] {
  const s = d as Structured;
  switch (s.t) {
    case "List":
    case "Set":
      return [s.elem];
    case "Map":
      return [s.key, s.val];
    case "Option":
      return [s.inner];
    case "Result":
      return [s.ok, s.err];
    case "Record":
      return s.fields.map((f) => f.desc);
    case "Tuple":
      return s.items;
    case "Union":
      return s.variants.flatMap((v) => v.payloads);
    case "Fix":
      return [s.body];
    default:
      return [];
  }
}

function stepsInto(d: GenDescData, name: string): boolean {
  const s = d as Structured;
  return (s.t === "Rec" && s.name === name) || partsOf(d).some((p) => stepsInto(p, name));
}

/** The rank of each recursive type in scope (see {@link boundRecursion}). */
type Ranks = ReadonlyMap<string, number>;

/**
 * How many steps back into a recursive type the shortest value of `d` takes:
 * none for a scalar, an empty collection or `None`; for a record or a tuple,
 * as many as its deepest part; for a union or a `Result`, as few as its
 * cheapest choice; and for a step into a type, one more than that type takes.
 * `Infinity` when no value of `d` is finite.
 */
function rank(d: GenDescData, ranks: Ranks): number {
  const s = d as Structured;
  switch (s.t) {
    case "Rec":
      return 1 + (ranks.get(s.name) ?? Number.POSITIVE_INFINITY);
    case "Fix":
      return fixRank(s, ranks);
    case "Result":
      return Math.min(rank(s.ok, ranks), rank(s.err, ranks));
    case "Union":
      return Math.min(...s.variants.map((v) => deepest(v.payloads, ranks)));
    case "Record":
    case "Tuple":
      return deepest(partsOf(d), ranks);
    default:
      return 0;
  }
}

function deepest(parts: GenDescData[], ranks: Ranks): number {
  return Math.max(0, ...parts.map((p) => rank(p, ranks)));
}

/**
 * A recursive type's rank: the least one its body agrees with. Starting from
 * "no finite value" and re-reading the body under the last answer can only
 * lower it, and stops when it no longer does.
 */
function fixRank(fix: { name: string; body: GenDescData }, ranks: Ranks): number {
  let r = Number.POSITIVE_INFINITY;
  for (;;) {
    const next = rank(fix.body, new Map(ranks).set(fix.name, r));
    if (next >= r) return r;
    r = next;
  }
}

/**
 * Mark where generation of a recursive type may stop, and refuse one that
 * cannot.
 *
 * Past its depth bound, the runtime's generator takes `None`, an empty
 * collection, and at each union or `Result` one of the choices marked `base` —
 * those of least rank — so every further step into a recursive type has a
 * shorter value still to finish, and the value ends. A choice node is marked
 * only when its choices differ in rank, which a type with no recursion in it
 * never does: its descriptor is the one it always was.
 *
 * A recursive type of infinite rank has no finite value: it cannot be built
 * without another of itself inside it (`type Inf = {v: Int, next: Inf}`).
 */
function boundRecursion(d: GenDescData, ranks: Ranks): GenDescData {
  const s = d as Structured;
  const bound = (p: GenDescData): GenDescData => boundRecursion(p, ranks);
  switch (s.t) {
    case "Fix": {
      const r = fixRank(s, ranks);
      if (r === Number.POSITIVE_INFINITY) {
        throw new NoGenerator(`"${s.name}" has no finite value`);
      }
      return { ...s, body: boundRecursion(s.body, new Map(ranks).set(s.name, r)) };
    }
    case "Union": {
      const variants = s.variants.map((v) => ({ ...v, payloads: v.payloads.map(bound) }));
      const base = cheapest(s.variants.map((v) => deepest(v.payloads, ranks)));
      return base ? { ...s, variants, base } : { ...s, variants };
    }
    case "Result": {
      const base = cheapest([rank(s.ok, ranks), rank(s.err, ranks)]);
      const tags = base?.map((i) => (i === 0 ? "Ok" : "Err"));
      const parts = { ok: bound(s.ok), err: bound(s.err) };
      return tags ? { ...s, ...parts, base: tags } : { ...s, ...parts };
    }
    case "List":
    case "Set":
      return { ...s, elem: bound(s.elem) };
    case "Map":
      return { ...s, key: bound(s.key), val: bound(s.val) };
    case "Option":
      return { ...s, inner: bound(s.inner) };
    case "Record":
      return { ...s, fields: s.fields.map((f) => ({ ...f, desc: bound(f.desc) })) };
    case "Tuple":
      return { ...s, items: s.items.map(bound) };
    default:
      return d;
  }
}

/** The indices of the least ranks, or `undefined` when every rank is the same. */
function cheapest(ranks: number[]): number[] | undefined {
  const least = Math.min(...ranks);
  if (ranks.every((r) => r === least)) return undefined;
  return ranks.flatMap((r, i) => (r === least ? [i] : []));
}

/**
 * Fold a refinement into a base descriptor so generation respects it (§8.3.2).
 *
 * Every predicate the runtime enforces belongs here, because the two answer
 * the same question from opposite ends: a generator that ignores a refinement
 * produces values the slot it is generating for would refuse, so the property
 * under test is run on states the app can never be in. While `email` / `url` /
 * `uuid` lowered to `(_v) => true` this was harmless and the descriptor
 * ignored them; enforcing them (#352) is what makes the omission visible.
 *
 * `regex` is the one predicate with no constraint to fold: generating from an
 * arbitrary pattern is a different problem from checking against one. §8.3.2
 * says so, and a `for-all` over a `regex`-refined type is a case to write by
 * hand.
 */
export function applyRefine(desc: GenDescData, r: Refinement | undefined): GenDescData {
  if (!r) return desc;
  const num = (i: number): number => (typeof r.args[i] === "number" ? (r.args[i] as number) : 0);
  switch (r.pred) {
    case "between":
      return desc.t === "Int" || desc.t === "Float" ? { ...desc, min: num(0), max: num(1) } : desc;
    case "positive":
      if (desc.t === "Int") return { ...desc, min: 1 };
      // Strictly above zero, because `positive` is `v > 0` and a generator
      // bounded at 0 can hand the check the one value it refuses. `EPSILON`
      // rather than `MIN_VALUE` (the smallest Float above zero): the bound is
      // the low end of a range the generator then samples, and a denormal one
      // buys nothing a representable gap does not.
      if (desc.t === "Float") return { ...desc, min: Number.EPSILON };
      return desc;
    case "negative":
      if (desc.t === "Int") return { ...desc, max: -1 };
      if (desc.t === "Float") return { ...desc, max: -Number.EPSILON };
      return desc;
    case "nonempty":
      return desc.t === "Text" ? { ...desc, minLen: 1 } : desc;
    case "len-eq":
      return desc.t === "Text" ? { ...desc, minLen: num(0), maxLen: num(0) } : desc;
    case "len-gt":
      return desc.t === "Text" ? { ...desc, minLen: num(0) + 1 } : desc;
    case "len-lt":
      return desc.t === "Text" ? { ...desc, maxLen: Math.max(0, num(0) - 1) } : desc;
    case "email":
    case "url":
    case "uuid":
      // A shape rather than a length: the generator builds an instance of the
      // form, so the value passes the same check the runtime applies.
      return desc.t === "Text" ? { ...desc, form: r.pred } : desc;
    case "one-of":
      // Independent of the base type — the choices *are* the domain.
      return { ...desc, oneOf: [...r.args] };
    default:
      return desc;
  }
}

/**
 * Every refinement a type carries, base outward.
 *
 * A type may be written with more than one `where` (spec/language.md §1.3.1),
 * and the predicates conjoin. The parser folds the first onto a `nominal` node
 * as a property and wraps each one after it, so the predicates sit on nested
 * nodes rather than in a list — and a named type reached through a `TypeRef`
 * hides its own underneath that. Reading exactly one layer, which is what this
 * module used to do, emitted the outermost predicate and dropped every other
 * (#353): `nominal Text where len-gt(3) where nonempty` accepted `"ab"`.
 *
 * The order is the one the chain the type denotes is read in, from the base
 * outward (§1.3.6, inv. 1). Inside a single type expression that is the order
 * the predicates are written in; across names it is not, and it does not depend
 * on which definition was declared first — on `type Handle = nominal Short
 * where len-gt(3)` over `type Short = Text where len-lt(9)`, `len-lt` comes
 * first wherever the two definitions sit in the file, because `Short` is what
 * `Handle` is declared over. It is the order a failed predicate is named in.
 *
 * The edges are the ones normalization (`unaliasType`) follows: an alias, a
 * `nominal` wrapper, a `where`, and a program-defined generic applied to its
 * arguments — `type NonEmpty(T) = T where nonempty` makes `NonEmpty(Handle)`
 * carry Handle's predicates and then `nonempty`. The walk stops at a structural
 * type: nothing written inside a record, a union or a container is a refinement
 * of the type itself, and a stdlib constructor (`List`, `Option`, …) has no
 * definition here to follow.
 *
 * `seen` is what makes a name written in terms of itself terminate: a generic
 * is guarded by its name like an alias. Its body is walked under `seen` plus
 * that name, but an argument is not part of the body — it is syntax of the
 * application site — so a parameter the body reaches is walked in the scope the
 * application was written in, under the `seen` in force there. Substituting the
 * argument into the body and walking it under the body's `seen` instead would
 * let the outer guard swallow a nested application of the same generic:
 * `NonEmpty(NonEmpty(Short))` would lose Short's predicates and the inner
 * `nonempty`. Arguments are sub-expressions of the caller's syntax, so the walk
 * still ends — `type Loop(T) = Loop(T) where nonempty` stops at the inner
 * `Loop`, and `type A = NonEmpty(A)` at the argument `A`. The cycle is E0009's
 * to report, and this walk still has to end on the way there.
 */
export function refinementsOf(t: TypeExpr, gen: Pick<GenCtx, "types">): Refinement[] {
  return collectRefinements(t, gen, { seen: new Set(), params: new Map() });
}

/**
 * Where a type expression is read: the names already entered on the way to it
 * and, inside a generic's body, what each parameter was applied to and where.
 * A parameter is looked up here before the program's definitions, so one that
 * shares its name with a top-level type reads as its argument; one with no
 * argument (an arity mismatch, the checker's to report) reads as nothing.
 */
type Scope = {
  seen: ReadonlySet<string>;
  params: ReadonlyMap<string, { arg: TypeExpr; scope: Scope } | undefined>;
};

function collectRefinements(t: TypeExpr, gen: Pick<GenCtx, "types">, scope: Scope): Refinement[] {
  switch (t.kind) {
    case "TypeRef":
    case "TypeApp": {
      if (t.kind === "TypeRef" && scope.params.has(t.name)) {
        const bound = scope.params.get(t.name);
        return bound ? collectRefinements(bound.arg, gen, bound.scope) : [];
      }
      if (scope.seen.has(t.name)) return [];
      const def = gen.types.get(t.name);
      if (!def) return [];
      // A plain alias's body has no parameters; a generic's are bound to the
      // arguments as written here, to be read back in this scope.
      const params = new Map<string, { arg: TypeExpr; scope: Scope } | undefined>();
      if (t.kind === "TypeApp") {
        def.params.forEach((p, i) => {
          const arg = t.args[i];
          params.set(p, arg ? { arg, scope } : undefined);
        });
      }
      return collectRefinements(def.body, gen, { seen: new Set([...scope.seen, t.name]), params });
    }
    case "TypeNominal":
    case "TypeRefinement": {
      const inner = collectRefinements(t.inner, gen, scope);
      return t.refinement ? [...inner, t.refinement] : inner;
    }
    // A type in its own right. Listed rather than defaulted so `assertNever`
    // reports the next node kind added to `TypeExpr` instead of silently losing
    // its refinements.
    case "TypePrim":
    case "TypeRecord":
    case "TypeUnion":
      return [];
    default:
      assertNever(t);
      return [];
  }
}

/**
 * The runtime test for a slot's type: every predicate it carries, conjoined.
 * `undefined` when the type carries none — the slot then has no `refine` at
 * all, which is what the runtime reads to mean "unrefined".
 */
export function refinementJs(t: TypeExpr, gen: GenCtx): string | undefined {
  const rs = refinementsOf(t, gen);
  if (rs.length === 0) return undefined;
  const bodies = rs.map(refinementBodyJs).filter((b): b is string => b !== undefined);
  // Every predicate this type carries is one the table has no lowering for —
  // which E0803 has already reported, because the parser accepts exactly the
  // names that table holds and every one of them lowers (#352). Emitting
  // nothing rather than the `(_v) => true` that used to stand here is the
  // point: a slot with no `refine` is one the runtime does not gate, where a
  // `refine` that answers `true` to every value reads as a gate and is not one.
  if (bodies.length === 0) return undefined;
  if (bodies.length === 1) return `(v) => ${bodies[0]}`;
  return `(v) => ${bodies.map((b) => `(${b})`).join(" && ")}`;
}

/**
 * One predicate's test, for the per-predicate entries the `error` tile reads.
 * `undefined` for a predicate with no lowering, as above.
 */
export { refinementToJs };
