import type { EffectDef, Program, SlotDef, TypeDef, TypeExpr } from "./ast.ts";
import { STANDARD_CAPABILITIES } from "./capabilities.ts";
import { type PrimName, STDLIB_TYPES } from "./stdlib-types.ts";

const PRIM_TS: Record<PrimName, string> = {
  Int: "number",
  Float: "number",
  Time: "number",
  Text: "string",
  Bool: "boolean",
  Unit: "null",
  Bytes: "Uint8Array",
  File: "{ name: string; size: number; type: string }",
  EffectId: "string",
};

const STDLIB_BY_NAME: ReadonlyMap<string, TypeDef> = new Map(STDLIB_TYPES.map((t) => [t.name, t]));

type Ctx = {
  /** Kumiki type name → the identifier it is declared under here. */
  userTypes: ReadonlyMap<string, string>;
  expanding: Set<string>;
  typeParams: ReadonlyMap<string, string>;
};

function tsOfType(t: TypeExpr, ctx: Ctx): string {
  switch (t.kind) {
    case "TypePrim":
      return PRIM_TS[t.name];
    case "TypeRef": {
      const local = ctx.typeParams.get(t.name) ?? ctx.userTypes.get(t.name);
      if (local) return local;
      const std = STDLIB_BY_NAME.get(t.name);
      if (!std || ctx.expanding.has(t.name)) return "unknown";
      return tsOfType(std.body, { ...ctx, expanding: new Set([...ctx.expanding, t.name]) });
    }
    case "TypeApp": {
      const arg = (i: number): string =>
        t.args[i] ? tsOfType(t.args[i] as TypeExpr, ctx) : "unknown";
      switch (t.name) {
        case "List":
          return `${wrap(arg(0))}[]`;
        case "Map":
          return `Record<string, ${arg(1)}>`;
        case "Set":
          return "Record<string, true>";
        case "Option":
          return `{ _tag: "Some"; _0: ${arg(0)} } | { _tag: "None" }`;
        case "Result":
          return `{ _tag: "Ok"; _0: ${arg(0)} } | { _tag: "Err"; _0: ${arg(1)} }`;
        case "Tuple":
          return `[${t.args.map((a) => tsOfType(a, ctx)).join(", ")}]`;
        default: {
          const declared = ctx.userTypes.get(t.name);
          if (declared) return `${declared}<${t.args.map((a) => tsOfType(a, ctx)).join(", ")}>`;
          const std = STDLIB_BY_NAME.get(t.name);
          if (!std || ctx.expanding.has(t.name)) return "unknown";
          return tsOfType(std.body, { ...ctx, expanding: new Set([...ctx.expanding, t.name]) });
        }
      }
    }
    case "TypeRecord":
      return `{ ${t.fields.map((f) => `${tsFieldName(f.name)}: ${tsOfType(f.type, ctx)}`).join("; ")} }`;
    case "TypeUnion":
      return t.variants.map((v) => variantTs(v.name, v.payloads, ctx)).join(" | ");
    case "TypeNominal":
    case "TypeRefinement":
      // Refinements/nominals erase to their base type in TS.
      return tsOfType(t.inner, ctx);
    default:
      return "unknown";
  }
}

const TS_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Quote a field name TypeScript cannot take bare. */
function tsFieldName(name: string): string {
  return TS_IDENT.test(name) ? name : JSON.stringify(name);
}

const HELPER_PROVIDER = "KumikiProvider";
const HELPER_SLOTS = "KumikiSlots";
const HELPER_PROVIDERS = "KumikiProviders";

const TS_RESERVED_TYPE_NAMES = [
  "any",
  "bigint",
  "boolean",
  "never",
  "number",
  "object",
  "string",
  "symbol",
  "undefined",
  "unknown",
  "void",
];

function allocTypeName(name: string, taken: Set<string>): string {
  const safe = name.replace(/-/g, "_");
  let candidate = safe;
  for (let n = 2; taken.has(candidate); n++) candidate = `${safe}_${n}`;
  taken.add(candidate);
  return candidate;
}

/** One tagged variant: `{ _tag: "Name" }` or `{ _tag: "Name"; _0: P0; … }`. */
function variantTs(name: string, payloads: TypeExpr[], ctx: Ctx): string {
  if (payloads.length === 0) return `{ _tag: ${JSON.stringify(name)} }`;
  const fields = payloads.map((p, i) => `_${i}: ${tsOfType(p, ctx)}`).join("; ");
  return `{ _tag: ${JSON.stringify(name)}; ${fields} }`;
}

/** Parenthesize a union so `T[]` binds correctly (`(A | null)[]`). */
function wrap(ts: string): string {
  return ts.includes("|") ? `(${ts})` : ts;
}

export function generateDts(program: Program): string {
  const types = program.defs.filter((d): d is TypeDef => d.kind === "TypeDef");
  const slots = program.defs.filter((d): d is SlotDef => d.kind === "SlotDef");
  const effects = program.defs.filter((d): d is EffectDef => d.kind === "EffectDef");
  const taken = new Set([
    HELPER_PROVIDER,
    HELPER_SLOTS,
    HELPER_PROVIDERS,
    ...TS_RESERVED_TYPE_NAMES,
  ]);
  const ctx: Ctx = {
    userTypes: new Map(types.map((t) => [t.name, allocTypeName(t.name, taken)])),
    expanding: new Set(),
    typeParams: new Map(),
  };

  const out: string[] = [];
  out.push("// Auto-generated by @kumikijs/compiler from the .kumiki source. Do not edit.");
  out.push("");
  out.push("/** A typed host implementation for one custom capability. */");
  out.push(`export type ${HELPER_PROVIDER}<In, Out> = (`);
  out.push("  input: In,");
  out.push("  caps: { has(c: string): boolean; provider(c: string): unknown },");
  out.push(") =>");
  out.push("  | { kind: 'ok'; value: Out }");
  out.push("  | { kind: 'err'; value: unknown }");
  out.push("  | Promise<{ kind: 'ok'; value: Out } | { kind: 'err'; value: unknown }>;");
  out.push("");

  for (const t of types) {
    const paramTaken = new Set(taken);
    const typeParams = new Map(t.params.map((p) => [p, allocTypeName(p, paramTaken)]));
    const params = t.params.length > 0 ? `<${[...typeParams.values()].join(", ")}>` : "";
    const body = tsOfType(t.body, { ...ctx, typeParams });
    out.push(`export type ${ctx.userTypes.get(t.name)}${params} = ${body};`);
  }
  if (types.length > 0) out.push("");

  out.push(`export interface ${HELPER_SLOTS} {`);
  for (const s of slots) out.push(`  ${tsFieldName(s.name)}: ${tsOfType(s.type, ctx)};`);
  out.push("}");
  out.push("");

  const custom = effects.filter((e) => !STANDARD_CAPABILITIES.has(e.cap));
  out.push("/** Host implementations for this app's custom capabilities. */");
  out.push(`export interface ${HELPER_PROVIDERS} {`);
  for (const e of custom) {
    const input = tsOfType(e.inType, ctx);
    const output = tsOfType(e.outType, ctx);
    out.push(`  ${JSON.stringify(e.cap)}?: ${HELPER_PROVIDER}<${input}, ${output}>;`);
  }
  out.push("}");
  out.push("");

  return out.join("\n");
}
